### ISSUE TITLE
Not show ads when i replace fragment

### ISSUE THREAD

**Issue by Secretbox1987** [adform/adform-android-sdk#10]
I use AdInlineLW into recycleview inside the fragment. If i replace that fragment to other fragment before loading ads then i come back, the ad dont show, i see empty space.

**Comment by Secretbox1987** [comment]
Now that I open another fragment, I set the isLoad property to the recycleview element model, when the ad receiver returns to success after I open another fragment. I install isLoad == false else == true, and when I return to the first fragment, I always run onResume and check isLoad if isLoad == false, that I delete the advertisement and create it again. It works for me. But can there be another solution?

**Comment by rprunskas** [comment]
Could you provide your current implementation code sample?

**Comment by suwaiphyo** [comment]
I also can not solve this issue. Could someone help? Please. @Secretbox1987 @rprunskas

**Comment by TobyEb** [comment]
I experience the same issue. when working with 2 fragments, e.g. Fragment A and Fragment B, the InlineAd shows up after creating Fragment A, when going to Fragment B and returning to Fragment A the ad won't show up again... 

Implementation is exactly like given in Wiki.

Logs:
```
ObservableService.resumeService():resume service
ObservableService.resumeService():ignoring resume, service is frozen. To start again, use startService.
```

**Comment by rprunskas** [comment]
Fixed in https://github.com/adform/adform-android-sdk/releases/tag/2.14.0
