### ISSUE TITLE
Banner doesn't show

### ISSUE THREAD

**Issue by Secretbox1987** [adform/adform-android-sdk#16]
I use AdInline for load ads. But ads with master tag id = 322482 returns onAdLoadSuccess(), but doesn't show.
I use "com.adform.advertising.sdk:advertising-sdk:2.13.2@aar'"
Adform sample app for testing master tag is closing when I try to load this ads.

**Comment by rprunskas** [comment]
Do you still experience this issue? Could you provide the output of the logcat?
