### ISSUE TITLE
Do not require extending Application class

### ISSUE THREAD

**Issue by emilaleborn** [adform/adform-android-sdk#18]
Forcing the application class to implement your AdApplicationService.ServiceListener is an antipattern (preventing dynamic loading of your SDK). Please provide another way of providing the AdApplicationService. One suggestion is using the init content provider pattern to make it always load before the app is instantiated.

**Comment by rprunskas** [comment]
You have to implement AdApplicationService.ServiceListener if you need expand or resize functionality. If you don't need that you could skip this part.
