### ISSUE TITLE
logging on by default

### ISSUE THREAD

**Issue by marekEniro** [adform/adform-android-sdk#2]
The SDK prints out lots of logs. Is there a way to turn logging off?

Example from our app:
10:55:45.624 21972-21972/? E/AdformSDK: onErrorLoading! A Parser-blocking, cross site (i.e. different eTLD+1) script, https://code.createjs.com/createjs-2015.11.26.min.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message.See https://www.chromestatus.com/feature/5718547946799104 for more details.
08-16 10:55:45.625 21972-21972/? W/AdformSDK: AdWebView$a.onConsoleMessage():A Parser-blocking, cross site (i.e. different eTLD+1) script, https://s1.adform.net/Banners/Elements/Files/58957/2069615/320x320.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message.See https://www.chromestatus.com/feature/5718547946799104 for more details.
08-16 10:55:45.625 21972-21972/? E/AdformSDK: onErrorLoading! A Parser-blocking, cross site (i.e. different eTLD+1) script, https://s1.adform.net/Banners/Elements/Files/58957/2069615/320x320.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message.See https://www.chromestatus.com/feature/5718547946799104 for more details.
08-16 10:55:45.626 21972-22077/? D/AdformSDK: AdWebView$b.shouldInterceptRequest():184466984 > 115434085 > shouldInterceptRequest:https://s1.adform.net/Banners/Elements/Files/58957/2069615/320x320.js
08-16 10:55:46.192 21972-22077/? D/AdformSDK: AdWebView$b.shouldInterceptRequest():184466984 > 115434085 > shouldInterceptRequest:https://track.adform.net/mobile/csimpr/?bn=19073586;msrc=1;adid=e99f31ef-7966-4e02-8ca9-905343c24232;smid=0;rtbwp=17nOlXG9bA41;rtbdata=ksTJ3VB-KkubYkC_30fNqDEptDQK_GhTzN8T5hlV-wthaZSPVPeQDrdmkfycAtpRf4wu13ajYeQwXwSw0kUp7ss81gDeitZgik3ww28QOrizSXZsYPbZqReGC-Iv8J1gw0R91RRRdncZw2gvZCmwBhmLevQIlM7WZPSVCRcBPzE1;csid=1936;adxvars=nVmjTUGG-LXU0t54j8hrswb8h-BOnTS5BlAxv21BSszV1frcAj9Btdi65v14lrzs_EYPHUrObQROHqqOmPQMFMruBkI-cWCciRo9UvoAY9JmT9kjsBh4moqm0iITCp_OLC8WFDGdQmKQDI46BZecxxnDaC9kKbAGGYt69AiUztYcW_FRQ3qRfBRXhfHH4_R8565ID3w7dFc6KjiiB6yUY1LqcnfhzwJE3AjYezygNu41;icid=3258498218057319606;icidt=636384705448943316;icido=1;rotseqno=1;srctype=5;set=pl-PL%7Cpl-PL%7C412X732%7C0%7C0%7C0%7C32%7C1%7C3%7C7%7C1;ord=78004678;unloadid=2445254391353947531;loc=http%3a%2f%2fandroid_assets
08-16 10:55:46.490 21972-21972/? D/AdformSDK: AdWebView$a.onProgressChanged():LoadProgress:90
08-16 10:55:46.608 21972-21972/? D/AdformSDK: AdWebView$a.onProgressChanged():LoadProgress:100
08-16 10:55:46.609 21972-21972/? D/AdformSDK: AdWebView$a.onProgressChanged():LoadProgress:100
08-16 10:55:46.609 21972-21972/? W/AdformSDK: AdWebView$b.onPageFinished():onPageFinished:file://android_assets/
08-16 10:55:46.610 21972-21972/? W/AdformSDK: SingleInnerContainer$1.a():onFinishLoading
08-16 10:55:46.610 21972-21972/? D/AdformSDK: updating view port size
08-16 10:55:46.651 21972-22001/? D/AdformSDK: GET https://track.adform.net/Serving/Event/?bn=19073586&event=175&rtbwp=17nOlXG9bA41&rtbdata=ksTJ3VB-KkubYkC_30fNqDEptDQK_GhTzN8T5hlV-wthaZSPVPeQDrdmkfycAtpRf4wu13ajYeQwXwSw0kUp7ss81gDeitZgik3ww28QOrizSXZsYPbZqReGC-Iv8J1gw0R91RRRdncZw2gvZCmwBhmLevQIlM7WZPSVCRcBPzE1&csid=1936&icid=3258498218057319606&icidt=636384705434881028&adxvars=nVmjTUGG-LXU0t54j8hrswb8h-BOnTS5BlAxv21BSszV1frcAj9Btdi65v14lrzs_EYPHUrObQROHqqOmPQMFMruBkI-cWCciRo9UvoAY9JmT9kjsBh4moqm0iITCp_OLC8WFDGdQmKQDI46BZecxxnDaC9kKbAGGYt69AiUztYcW_FRQ3qRfBRXhfHH4_R8565ID3w7dFc6KjiiB6yUY1LqcnfhzwJE3AjYezygNu41
08-16 10:55:46.765 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:394,width:320,height:160}, defaultPosition: {x:45,y:394,width:320,height:160}, screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, supports:{tel:true, sms:true, storePicture:true, calendar:true, inlineVideo:true, viewablePercentage:true}, placementType:"inline", state:"default"}
08-16 10:55:46.953 21972-21972/? W/AdformSDK: SingleInnerContainer$3.a():Event broadcast: stateChange / [default]
08-16 10:55:46.955 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {viewable: true}
08-16 10:55:46.957 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {viewablePercentage: 100}
08-16 10:55:46.985 21972-21972/? W/AdformSDK: SingleInnerContainer$3.a():Event broadcast: ready / []
08-16 10:55:47.014 21972-21972/? W/AdformSDK: SingleInnerContainer$3.a():Event broadcast: viewableChange / [true]
08-16 10:55:47.014 21972-21972/? W/AdformSDK: SingleInnerContainer$3.a():Event broadcast: viewablePercentageChange / [100]
08-16 10:55:47.214 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:394,width:320,height:160}}
08-16 10:55:47.426 21972-22001/? D/AdformSDK: networkResponse: i, it took 775ms to complete
08-16 10:55:47.446 21972-21972/? E/AdformSDK: BaseCoreContainer$1.a():Impression loaded successfully
08-16 10:55:47.486 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:394,width:320,height:160}}
08-16 10:55:47.492 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:394,width:320,height:160}, defaultPosition: {x:45,y:394,width:320,height:160}}
08-16 10:55:47.513 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:394,width:320,height:160}}
08-16 10:55:47.517 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:394,width:320,height:161}, defaultPosition: {x:45,y:394,width:320,height:161}}
08-16 10:55:47.537 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:382,width:320,height:161}}
08-16 10:55:47.541 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:382,width:320,height:166}, defaultPosition: {x:45,y:382,width:320,height:166}}
08-16 10:55:47.611 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:326,width:320,height:166}}
08-16 10:55:47.615 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:326,width:320,height:186}, defaultPosition: {x:45,y:326,width:320,height:186}}
08-16 10:55:47.632 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:292,width:320,height:186}}
08-16 10:55:47.636 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:292,width:320,height:199}, defaultPosition: {x:45,y:292,width:320,height:199}}
08-16 10:55:47.651 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:277,width:320,height:199}}
08-16 10:55:47.655 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:277,width:320,height:207}, defaultPosition: {x:45,y:277,width:320,height:207}}
08-16 10:55:47.672 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:263,width:320,height:207}}
08-16 10:55:47.677 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:263,width:320,height:215}, defaultPosition: {x:45,y:263,width:320,height:215}}
08-16 10:55:47.690 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:251,width:320,height:215}}
08-16 10:55:47.694 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:251,width:320,height:222}, defaultPosition: {x:45,y:251,width:320,height:222}}
08-16 10:55:47.702 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:251,width:320,height:222}}
08-16 10:55:47.712 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:240,width:320,height:222}}
08-16 10:55:47.715 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:240,width:320,height:231}, defaultPosition: {x:45,y:240,width:320,height:231}}
08-16 10:55:47.729 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:224,width:320,height:231}}
08-16 10:55:47.733 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:224,width:320,height:248}, defaultPosition: {x:45,y:224,width:320,height:248}}
08-16 10:55:47.747 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:217,width:320,height:248}}
08-16 10:55:47.750 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:217,width:320,height:256}, defaultPosition: {x:45,y:217,width:320,height:256}}
08-16 10:55:47.763 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:213,width:320,height:256}}
08-16 10:55:47.766 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:213,width:320,height:264}, defaultPosition: {x:45,y:213,width:320,height:264}}
08-16 10:55:47.779 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:210,width:320,height:264}}
08-16 10:55:47.783 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:210,width:320,height:272}, defaultPosition: {x:45,y:210,width:320,height:272}}
08-16 10:55:47.796 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:208,width:320,height:272}}
08-16 10:55:47.799 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:208,width:320,height:279}, defaultPosition: {x:45,y:208,width:320,height:279}}
08-16 10:55:47.812 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:207,width:320,height:279}}
08-16 10:55:47.816 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:207,width:320,height:286}, defaultPosition: {x:45,y:207,width:320,height:286}}
08-16 10:55:47.830 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:206,width:320,height:286}}
08-16 10:55:47.834 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:206,width:320,height:292}, defaultPosition: {x:45,y:206,width:320,height:292}}
08-16 10:55:47.847 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:206,width:320,height:292}}
08-16 10:55:47.850 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:206,width:320,height:298}, defaultPosition: {x:45,y:206,width:320,height:298}}
08-16 10:55:47.863 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:205,width:320,height:298}}
08-16 10:55:47.867 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:205,width:320,height:304}, defaultPosition: {x:45,y:205,width:320,height:304}}
08-16 10:55:47.880 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:205,width:320,height:304}}
08-16 10:55:47.883 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:205,width:320,height:308}, defaultPosition: {x:45,y:205,width:320,height:308}}
08-16 10:55:47.896 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:205,width:320,height:308}}
08-16 10:55:47.900 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:205,width:320,height:312}, defaultPosition: {x:45,y:205,width:320,height:312}}
08-16 10:55:47.913 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:205,width:320,height:312}}
08-16 10:55:47.916 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:205,width:320,height:315}, defaultPosition: {x:45,y:205,width:320,height:315}}
08-16 10:55:47.924 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:205,width:320,height:315}}
08-16 10:55:47.930 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:205,width:320,height:315}}
08-16 10:55:47.933 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:205,width:320,height:317}, defaultPosition: {x:45,y:205,width:320,height:317}}
08-16 10:55:47.945 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:205,width:320,height:317}}
08-16 10:55:47.948 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:205,width:320,height:319}, defaultPosition: {x:45,y:205,width:320,height:319}}
08-16 10:55:47.960 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:205,width:320,height:319}}
08-16 10:55:47.963 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:205,width:320,height:319}, defaultPosition: {x:45,y:205,width:320,height:319}}
08-16 10:55:47.977 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:205,width:320,height:319}}
08-16 10:55:47.981 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {screenSize: {width:411, height:731}, maxSize: {width:411, height:683}, currentPosition: {x:45,y:205,width:320,height:320}, defaultPosition: {x:45,y:205,width:320,height:320}}
08-16 10:55:48.139 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {currentPosition: {x:45,y:205,width:320,height:320}}
08-16 11:04:33.289 21972-21972/? D/AdformSDK: AdInline.b()::class com.adform.sdk.pub.views.AdInline:com.adform.sdk.pub.views.AdInline{afebe28 V.E...... ........ 94,26-934,866 #62487}
08-16 11:04:33.291 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {viewable: false}
08-16 11:04:33.297 21972-21972/? E/AdformSDK: AdWebView.a():184466984 > 115434085 > {viewablePercentage: 0}
08-16 11:04:33.309 21972-21972/? D/AdformSDK: d.d():pause service
08-16 11:04:33.311 21972-21972/? D/AdformSDK: d.d():service not running nothing to pause
08-16 11:04:33.429 21972-21972/? W/AdformSDK: SingleInnerContainer$3.a():Event broadcast: viewableChange / [false]
08-16 11:04:33.429 21972-21972/? W/AdformSDK: SingleInnerContainer$3.a():Event broadcast: viewablePercentageChange / [0]

**Comment by marekEniro** [comment]
Could someone have a look at this issue please?

**Comment by andriusmisiunas** [comment]
Thank you for notifying us - we are looking into the issue and will let you know.

**Comment by rprunskas** [comment]
Hello, at the moment it is not possible to turn off the logging programically. There is workaround using Proguard, adform sdk log class: com.adform.sdk.network.utils.Log

**Comment by rogierdna** [comment]
But it makes harder to work with debug builds. 
Yes, proguard will delete logs in production code, but in debug mode, it's very hard to filter out messages.
Proper solution would be to disable logging from SDK.
