### ISSUE TITLE
Issue with ads loading

### ISSUE THREAD

**Issue by Secretbox1987** [adform/adform-android-sdk#20]
Hello! I have issue with ads loading:
SERVER error. Error parsing entity. (TagData entity is empty)
I use masterTagId = 322490
Please, help me to fix it

**Comment by andriusmisiunas** [comment]
Hello,

This error means that no ad was returned from ADX. Please check placement settings, targeting settings. Let us know if issue persists.

**Comment by Secretbox1987** [comment]
Somtimes ads loads successfully, but often the one loads failed. In both cases I use the same masterTagId
