### ISSUE TITLE
latest release of com.google.android.gms:play-services-ads is not working

### ISSUE THREAD

**Issue by sturmann123** [adform/adform-android-sdk#26]
We can’t use the latest release of com.google.android.gms:play-services-ads, the newest version which works is
16.0.0.
Build with 'com.google.android.gms:play-services-ads:18.2.0' give the following error on app start:

`2019-09-18 15:48:54.228 18379-18379/? E/AndroidRuntime: FATAL EXCEPTION:
main
Process: XXXApp.dbg, PID: 18379
java.lang.RuntimeException: Unable to get provider
com.google.android.gms.ads.MobileAdsInitProvider:
java.lang.IllegalStateException:
**************************************************************************
****
* The Google Mobile Ads SDK was initialized incorrectly. AdMob
publishers *
* should follow the instructions here:
*
* https://googlemobileadssdk.page.link/admob-android-update-manifest
*2
* to add a valid App ID inside the AndroidManifest.
*
* Google Ad Manager publishers should follow instructions here:
*
* https://googlemobileadssdk.page.link/ad-manager-android-updatemanifest.
*
**************************************************************************
****
at
android.app.ActivityThread.installProvider(ActivityThread.java:6445)
at
android.app.ActivityThread.installContentProviders(ActivityThread.java:598
7)
at
android.app.ActivityThread.handleBindApplication(ActivityThread.java:5902)
at android.app.ActivityThread.access$1100(ActivityThread.java:200)
at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6718)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.ja
va:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException:
**************************************************************************
****
* The Google Mobile Ads SDK was initialized incorrectly. AdMob
publishers *
* should follow the instructions here:
*
* https://googlemobileadssdk.page.link/admob-android-update-manifest
*
* to add a valid App ID inside the AndroidManifest.
*
* Google Ad Manager publishers should follow instructions here:
*
* https://googlemobileadssdk.page.link/ad-manager-android-updatemanifest.
*
**************************************************************************
****
at
com.google.android.gms.internal.ads.zzxi.attachInfo(com.google.android.gms
:play-services-ads-lite@@18.2.0:27)
at
com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(com.google.and
roid.gms:play-services-ads-lite@@18.2.0:3)
at
android.app.ActivityThread.installProvider(ActivityThread.java:6440)
... 10 more`

**Comment by rprunskas** [comment]
Fixed in 2.14.0
