### ISSUE TITLE
AdInline doesn’t show up again when navigating back to the fragment

### ISSUE THREAD

**Issue by sturmann123** [adform/adform-android-sdk#27]
AdInline doesn’t show up again when navigating back to the fragment where it was displayed, when creating the
fragment again it works just fine. There is also an open Github issue for this bug.

`2019-09-18 16:01:55.984 19200-
19200/XXX.dbg D/AdformSDK:
AdInline.onPause()::class
com.adform.sdk.pub.views.AdInline:com.adform.sdk.pub.views.AdInline{919b6a
d V.E...... ........ 1,1405-1079,1536 #7f090024 app:id/adContainer}
2019-09-18 16:01:55.985 19200-
19200/XXX.dbg E/AdformSDK:
AdWebView.fireChangeEventForProperty():152680109 > 162608861 > {viewable:
false}
2019-09-18 16:01:55.986 19200-
19200/XXX.dbg E/AdformSDK:
AdWebView.fireChangeEventForProperty():152680109 > 162608861 >
{viewablePercentage: 0}
2019-09-18 16:01:55.987 19200-
19200/XXX.dbg D/AdformSDK:
ObservableService.pauseService():pause service
2019-09-18 16:01:55.987 19200-
19200/XXX.dbg D/AdformSDK:
ObservableService.pauseService():service not running nothing to pause
2019-09-18 16:01:56.091 19200-
19200/XXX.dbg W/AdformSDK:
SingleInnerContainer$3.onNativePrint():Event broadcast: viewableChange /
[false]
2019-09-18 16:01:56.091 19200-
19200/XXX.dbg W/AdformSDK:
SingleInnerContainer$3.onNativePrint():Event broadcast:
viewablePercentageChange / [0]
2019-09-18 16:01:56.390 19200-
19648/XXX.dbg D/AdformSDK:
AdWebView$AdWebViewClient.shouldInterceptRequest():152680109 > 162608861 >
shouldInterceptRequest:https://track.adform.net/serving/unload/?
version=15&msrc=1&unload=3865246505044348399@@32423157,2970508872762474933
,100|17598|0|0|0|0|0|0|0||17598|0|2519|f7a8b99e049e4dd5aede720fb993f196|||
1|0|0|jgQm7pzYLVV0p8MCzR8AkNcQ8Q7YuXWZr_5JpdXq6LvIcMGSiXv0bP8-
fXTMqb8Q6HgpkVnL0bZjDg0Gpj7u8pv2CVWUryxUvfxqE7JvaYjCADjTWSFBgO8_
7rsP1jj0|-
baUWB26K1DZrxDq0SmVNARaEbkY2HTnlBX02Sw0TiR60D4UmcKO_xTT63AfBrmpsVjylodXdwl
adform_problems.md 9/18/2019
4 / 52
d6YmC6r0tMa7zmYF0VkxBo0pvVeo_Uai6dNrpLoPh3-09JN9H1IdqxNjJYSO0uNPXj7nFx2a-
X4DIWNUXAvAlMRQrYB2XCOC28ocqmhuFh-
TPIJPUfFzLRmgVdzGPGwPSPymZStG_P0LTcmP4FsqiBROHXF4hvGq5pbmXhAqYYsWjAexNyLOV
0||01|1
2019-09-18 16:02:04.654 19200-
19200/XXX.dbg D/AdformSDK:
AdInline.onResume()::class
com.adform.sdk.pub.views.AdInline:com.adform.sdk.pub.views.AdInline{9cc9ad
9 G.E...... ......I. 0,0-0,0 #7f090024 app:id/adContainer}
2019-09-18 16:02:04.657 19200-
19200/XXX.dbg E/AdformSDK:
BaseAnimator.show():View that was scheduled for animation already has a
parent.
2019-09-18 16:02:04.775 19200-
19200/XXX.dbg D/AdformSDK:
ObservableService.resumeService():resume service
2019-09-18 16:02:04.775 19200-
19200/XXX.dbg D/AdformSDK:
ObservableService.resumeService():ignoring resume, service is frozen. To
start again, use startService.
2019-09-18 16:02:16.407 19200-
19200/XXX.dbg D/AdformSDK:
AdInline.onPause()::class
com.adform.sdk.pub.views.AdInline:com.adform.sdk.pub.views.AdInline{9cc9ad
9 G.E...... ......I. 0,0-0,0 #7f090024 app:id/adContainer}
2019-09-18 16:02:16.408 19200-
19200/XXX.dbg D/AdformSDK:
ObservableService.pauseService():pause service
2019-09-18 16:02:16.409 19200-
19200/XXX.dbg D/AdformSDK:
ObservableService.pauseService():service not running nothing to pause
2019-09-18 16:02:20.265 19200-
19200/XXX.dbg D/AdformSDK:
AdInline.onResume()::class
com.adform.sdk.pub.views.AdInline:com.adform.sdk.pub.views.AdInline{b9346a
e G.E...... ......I. 0,0-0,0 #7f090024 app:id/adContainer}
2019-09-18 16:02:20.269 19200-
19200/XXX.dbg E/AdformSDK:
BaseAnimator.show():View that was scheduled for animation already has a
parent.
2019-09-18 16:02:20.356 19200-
19200/XXX.dbg D/AdformSDK:
ObservableService.resumeService():resume service
2019-09-18 16:02:20.357 19200-
19200/XXX.dbg D/AdformSDK:
ObservableService.resumeService():ignoring resume, service is frozen. To
start again, use startService.`

**Comment by rprunskas** [comment]
Fixed in 2.14.0
