### ISSUE TITLE
no advertising displayed and error

### ISSUE THREAD

**Issue by adegrawebpills** [adform/adform-android-sdk#4]
Hello we are using your SDK on our application mobile in standard mode.

Your SDK return this error 

09:52:16.818 9832-14973/com.adform.sample.app D/AdformSDK: Contract response:{"adServing":{"version":"1.0","ad":{"trackingUrlBase":"http://track.adform.net","refreshInterval":0,"tagData":null,"BannerSize":{"Width":320,"Height":50}}}}
09:52:16.828 9832-14973/com.adform.sample.app E/AdformSDK: Error parsing entity. (TagData entity is empty)
09:52:16.828 9832-14973/com.adform.sample.app D/AdformSDK: networkResponse: null, it took 109ms to complete
09:52:16.828 9832-9832/com.adform.sample.app E/AdformSDK: AdInline.onContractLoaded():SERVER error. Error parsing entity. (TagData entity is empty)

**Comment by rprunskas** [comment]
Hello, ADX service hasn't returned any ad. Please contact Adform support they might help you.
