### ISSUE TITLE
Slowly load AdInline and AdInlineLW

### ISSUE THREAD

**Issue by Secretbox1987** [adform/adform-android-sdk#5]
We use AdInline, we call loadAd(), but it load for 3-5 seconds
We use implementation 'com.google.android.gms:play-services-ads:11.8.0'
    implementation 'com.adform.advertising.sdk:advertising-sdk:2.11.0@aar'

**Comment by Secretbox1987** [comment]
How loading more faster

**Comment by rprunskas** [comment]
Ad loading speed mainly depends on network connection, device, server load, ad itself. I'm closing this issue since it is not relevant with the Adform SDK.
