### ISSUE TITLE
Interstitial is still showing in manual mode

### ISSUE THREAD

**Issue by DominList** [adform/adform-android-sdk#6]
Interstitial is still showing even if I set:    

 ` interstitial.setOverridePagerPageChangeListener(true);`

Is there any simple way to show it once upon a time ( ex. 15 minutes )?

**Comment by rprunskas** [comment]
If you want to implement custom interstitial showing logic you need to set:
`interstitial.setOverridePagerPageChangeListener(false);`

Then add page change listener with your custom logic for showing ads. Basically to show an interstitial you need to `increaseShownPageCount()`. When count is reached which is set via `setMaxPageChange(count)`, ad is shown. So if you implement a method which allows to increase page count only sometimes, you will get your desired behavior. 

 ```
pager.setOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
            }

            @Override
            public void onPageSelected(int position) {
                if(customLogicToIncreaseCount()){
                    adInterstitial.increaseShownPageCount();
                }
            }

            @Override
            public void onPageScrollStateChanged(int state) {
            }
        });
```

**Comment by DominList** [comment]
I have `setMaxPageChange(10)` and increasing shown page every page selected:

```
@Override
public void onPageSelected(int position) {
    adInterstitial.increaseShownPageCount()
}
```

The result I've got was even 80 times page change without visible ad. One other time 35  page changes and after first appearing of interstitial, it is shown once for 3 to 7 page changes.
The conclusion is that Interstitial works unpredictable.

Another question is, maybe you know, what is for `interstitial.showAd()` method? 
Documentation is very poor - just simply say nothing about it.

**Comment by rprunskas** [comment]
If you set `setMaxPageChange(10)` that does not mean that ad will be shown exactly after 10 page changes. It is possible that ad wasn't loaded. If ad is loaded page change could would be reset to 0. `pageChangeCount = 0;`

If I use this code, ad is shown after 10 pages changes, not less. If you still gave issues, please give use your implementations I we will check on our side.

```
 adInterstitial.setMaxPageChange(10);

        adInterstitial.setOverridePagerPageChangeListener(false);
        pager.setOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
            }

            @Override
            public void onPageSelected(int position) {
                adInterstitial.increaseShownPageCount();
            }

            @Override
            public void onPageScrollStateChanged(int state) {
            }
        });
```


`showAd() ` method shows ad immediately if it is loaded.

**Comment by DominList** [comment]
I have used the same implementation in the lightweight test app - it was working quite well - ad was shown every 12 pages (when `setMaxPageChange(10)`). However in the target app it was not working this way. What I suppose: ad working can be disturbed by using background thread in the one queue? (I mean `AsyncTask` which I use every page change).

For me at the moment the problem is solved if I can change the show frequency from user account panel. However is good to know how Interstitial works for the society.
