### ISSUE TITLE
Interstitial  .isShown returns true if add is not displayed on the screen

### ISSUE THREAD

**Issue by DominList** [adform/adform-android-sdk#7]
Interstitial  .isShown returns true if add is not displayed on the screen. In this case I want to remove from the screen all menu widgets. How can I get the purpose with current AdForm API?

**Comment by rprunskas** [comment]
`isShown()` method returns visibility by status flag. View could be not in the screen but it status flag could be visible. You could read more here:
[View](https://developer.android.com/reference/android/view/View.html)

Please use AdInterstitialStateListener for your desired behaviour:

```
adInterstitial.setStateListener(new AdInterstitial.AdInterstitialStateListener() {
            @Override
            public void onAdShown() {
                
            }

            @Override
            public void onAdClose() {

            }
        });
```

**Comment by DominList** [comment]
Thanks, that worked for me.
