### ISSUE TITLE
AdInline Recycling

### ISSUE THREAD

**Issue by rogierdna** [adform/adform-android-sdk#8]
I have a question about Adform Android SDK. 
I'm interested if SDK `adInline` handles Android View Recycling.
Since I saw that in some cases when scrolling same Ad was repeated… 

Is there any method for `AdInline` view so that I can clear out Ad while binding in ViewHolder and load new ad in same container?

Since this is the case with RecyclerView ViewHolder.

**Comment by rprunskas** [comment]
If you want to show new ad in the same container, you need to remove the old one and create a new `AdInline`.
