### ISSUE TITLE
Inline SmartSize

### ISSUE THREAD

**Issue by ghost** [adform/adform-android-sdk#9]
Hello,
I'm using setAdSize(new SmartAdSize()); but top-most and bottom-most parts are cut.
Two files are attached. One file shows the original ad and the other one is its view on a device.
Would you please resolve the issue?
Thanks in advance.

![320x50](https://user-images.githubusercontent.com/12443739/38196507-335a32ca-368c-11e8-883e-dbe1be3241f5.png)
![problem](https://user-images.githubusercontent.com/12443739/38196508-338106a2-368c-11e8-97f0-39bad21f595f.png)

**Comment by rprunskas** [comment]
Hello,

If you use smart ad size, your ad will be displayed in 50dp height(for phones). Please check if your banner could fit in this size. 

Smart ad size documentation - https://github.com/adform/adform-android-sdk/wiki/Advanced-integration-of-Inline-Ad#smart-ad-size
